apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uciplink-log
  namespace: ers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: uciplink-log
  storageClassName: manual